---
title: A quarto PCI template using the Typst backend
date: "2024-01-01"
author:
  - "Camille Noûs"
  - "Second Author"
  - "Last Author"
volume: "Vol. XX (2024), article eXX"
doi: "https://doi.org/10.24072/pci.xxx"
format:
  pci-typst: default
abstract: |
  The process of scientific writing is often tangled up with the intricacies
  of typesetting, leading to frustration and wasted time for researchers.
  In this paper, we introduce Typst, a new typesetting system designed 
  specifically for scientific writing. Typst untangles the typesetting process,
  allowing researchers to compose papers faster. In a series of experiments we
  demonstrate that Typst offers several advantages, including faster document
  creation, simplified syntax, and increased ease-of-use.
bibliography: sample.bib
---

# Introduction

This is an example of text. This realization is especially important because it can flip around our expectations about which species expand fast, and how to manage them. We tend to think of initial colonization and long-term abundance as two independent axes of variation among species or indeed as two ends of a spectrum, in the classic competition-colonization tradeoff [@levins1971regional]. When both play into invasion speed, good dispersers might not outrun good competitors. This is useful knowledge, whether we want to contain an invasion or secure a reintroduction.

In their study "When higher carrying capacities lead to faster propagation",
#cite(<levins1971regional>, form: "prose") combine mathematical analysis, Individual-Based simulations and experiments to show that various mechanisms can cause pushed fronts, whose speed increases with the carrying capacity K of the species. Rather than focus on one particular angle, the authors endeavor to demonstrate that this qualitative effect appears again and again in a variety of settings.

It is perhaps surprising that this notable and general connection between K and invasion speed has managed to garner so little fame in ecology. A large fraction of the literature employs the venerable Fisher-KPP reaction-diffusion model, which combines local logistic growth with linear diffusion in space. This model has prompted both considerable mathematical developments [@crooks2004spatial] and many applications to modelling real invasions [@shigesada1997biological]. But it only allows pulled fronts, driven by the small populations at the edge of a species range, with a speed that depends only on their initial growth rate r.


# More Information

You can learn more about creating custom Typst templates here: 

<https://quarto.org/docs/prerelease/1.4/typst.html#custom-formats>



